export const HERO_PHOTO_COUNT = 8;
export const HERO_ROTATION_DELAY_MS = 2500;
export const HERO_CROSSFADE_DURATION_MS = 700;
export const HERO_IMAGE_SIZES = "100vw";

export const LIGHTBOX_IMAGE_TRANSITION_MS = 250;
export const LIGHTBOX_CLOSE_DURATION_MS = 150;
export const LIGHTBOX_PRELOAD_FORWARD_COUNT = 3;
export const LIGHTBOX_PRELOAD_BACKWARD_COUNT = 2;
export const LIGHTBOX_MAX_WIDTH_VIEWPORT_PERCENT = 95;
export const LIGHTBOX_MAX_HEIGHT_VIEWPORT_PERCENT = 95;
export const LIGHTBOX_IMAGE_SIZES = `${LIGHTBOX_MAX_WIDTH_VIEWPORT_PERCENT}vw`;
